"use client";

import React from "react";
import { Button } from "@/components/ui/button";
import type { AiAuditLog } from "@/lib/apiTypes";
import { fetchAiAudit, downloadAiAudit } from "@/lib/api";

type AiDecisionLogTabProps = {
  caseId: string;
  loader?: (caseId: string) => Promise<AiAuditLog>;
  downloader?: (caseId: string) => Promise<void>;
};

export default function AiDecisionLogTab({ caseId, loader = fetchAiAudit, downloader = downloadAiAudit }: AiDecisionLogTabProps) {
  const [audit, setAudit] = React.useState<AiAuditLog | null>(null);
  const [error, setError] = React.useState<string | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [downloading, setDownloading] = React.useState(false);

  React.useEffect(() => {
    let cancelled = false;
    const load = async () => {
      setLoading(true);
      try {
        const data = await loader(caseId);
        if (!cancelled) {
          setAudit(data);
          setError(null);
        }
      } catch (err) {
        if (!cancelled) {
          const message = err instanceof Error ? err.message : "Unable to load AI audit.";
          setError(message);
          setAudit(null);
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    };
    load();
    return () => {
      cancelled = true;
    };
  }, [caseId, loader]);

  const handleDownload = async () => {
    try {
      setDownloading(true);
      await downloader(caseId);
    } catch (err) {
      const message = err instanceof Error ? err.message : "Download failed";
      setError(message);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="space-y-3">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div>
          <h4 className="text-sm font-semibold text-slate-700">Decision Log (JSON)</h4>
          <p className="text-xs text-slate-500">Transparency artifact generated by the Agentic AI Decisioning Engine.</p>
        </div>
        <Button type="button" onClick={handleDownload} disabled={downloading}>
          {downloading ? "Preparing…" : "Download Audit"}
        </Button>
      </div>

      {loading && <p className="text-sm text-muted-foreground">Loading audit trail…</p>}
      {error && !loading && (
        <div className="rounded-md border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">
          {error}
        </div>
      )}
      {audit && !loading && (
        <pre
          className="max-h-80 overflow-auto rounded-md border border-slate-200 bg-slate-950/90 p-3 text-xs text-slate-50"
          aria-label="AI decision log JSON"
        >
          {JSON.stringify(audit, null, 2)}
        </pre>
      )}
    </div>
  );
}
